### ISSUE TITLE
_slow_path_step_body is broken

### ISSUE THREAD

**Issue by edgarsi** [Erotemic/progiter#32]
When running in non-homogeneous mode, only the first outputs are ever done. The problem is `_slow_path_step_body` since it now calls `_update_all_calculations` [every time](
https://github.com/Erotemic/progiter/pull/29/commits/d19c00f500aaa4f7adfc960572201c4846aa73d8#diff-c46794fdcfa889f96c27387a7d70e11ca31fc440c61f06fd300517d01495a87dR548). This causes `self._between_time` to be time between iterations, and if the iterations are faster than `self.time_thresh`, no output is ever done. Basically, `_update_measurements` simply can't be called every time - `_between_time` is used as the time between outputs. Homogeneous calculation needs to calculate iteration times independently.

**Comment by Erotemic** [comment]
This is on my list of things to look at, but it may take me awhile. Any patches to fix the issue would be appreciated.

**Comment by Erotemic** [comment]
I see the problem. The issue is that `update_measurements` is doing more than that. It's always updating the "previous" measurements which really should only be updated if we've made a display. Working on a patch that will try to refactor this behavior and cleanup the code.

**Comment by Erotemic** [comment]
Some of the code refactor ideas I'm working with include:

* creating a Measurement named tuple to bundle the iteration index and time of each measurement.
* tracking a measurement for the most recent display as well as the two most recent time checks. Not tracking the time of the previous display is a root cause of this bug. We were using `_between_time` (which is really the time between calls to `time.time()` as if it was the time since the last measurement).

**Comment by Erotemic** [comment]
I believe #34 will fix this. I wrote a debug tool to help organize the state of progiter at important points in time. For each timestep I insert a row into a table that describes the current iteration stats and if we did a display / time check. 

For a homogeneous=False example it looks like this:

![image](https://user-images.githubusercontent.com/3186211/220244057-95071b6a-6af8-4ec4-87e9-f2bd48ff9803.png)

For homogeneous cases it looks pretty reasonable. I should likely this procedure up with some real tests, but I want to get pypi unbroken sooner rather than later. I'll merge and upload if existing dashboards pass.
